### ISSUE TITLE
Plugins do not work with Maven 3.1.0

### ISSUE THREAD

**Issue by brettporter** [torquebox/jruby-maven-plugins#50]
The plugins use underlying implementation classes from Aether, which was replaced in Maven 3.1.0 with a version distributed by Eclipse with different package naming conventions. This causes the following failures:

```
[WARNING] Error injecting: de.saumya.mojo.ruby.gems.DefaultGemManager
java.lang.NoClassDefFoundError: org/sonatype/aether/RepositorySystemSession
```

From what I can see, this is only used for constructing projects and further injecting the session. This should be able to be done with the normal Maven APIs that work all the way back to Maven 2.

Unfortunately, I only use a subset of the plugins, so I don't know that I could adequately test any changes to that affect. How extensive are your ITs?
